import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Document from './_document'
import Link from 'next/link'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })

// Write comments about meetings, upvote comments about meeting, rate meeting
// Be able to create user account with authentication. User having a profile as well as data determined by other users
// Logging in
// View meetings


//
//


// Make a view that takes you to the individual meeting page
// Figure out how to make a list of meeting info and pass it into the table
// Make a table that accepts the dynamic information related to those columns
// Make a table that displays the names of the relevant columns


export default function Home() {
  return (
    <>
      <Head>
        <title>Editing and Understanding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
           
            <Link href={"/MeetingDisplay"}><strong>Link to meeting Display</strong></Link>
          </p>
          <div>
            <a
              href="/MeetingDisplay"
              target="_blank"
              rel="noopener noreferrer"
            >
              
            </a>
           
          </div>
        </div>

        

        <div className={styles.grid}>
          <a
            href="https://www.google.com"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Link to google. Testing.
            </p>
          </a>



        </div>
      </main>
    </>
  )
}

