import React from 'react';

const DummyData =
[
    {
      "name": "Sundown Serenity",
      "slug": "sundown-serenity-8",
      "day": 0,
      "time": "19:00",
      "end_time": "20:30",
      "location": "Grace Hall",
      "group": "Twilight Fellowship",
      "notes": "Parking available behind the building.",
      "updated": "2020-11-19 17:55:12",
      "url": "https://twilightaa.net/sundown-serenity",
      "types": ["C", "T"],
      "address": "789 Oak Avenue",
      "city": "Sunsetville",
      "state": "TX",
      "postal_code": "12345",
      "country": "US",
      "approximate": "no"
    },
    {
      "name": "Moonlit Melodies",
      "slug": "moonlit-melodies-3",
      "day": 2,
      "time": "20:30",
      "end_time": "22:00",
      "location": "Silver Moon Pavilion",
      "group": "Nocturnal Harmony",
      "notes": "Bring your own seating.",
      "updated": "2022-04-15 14:22:30",
      "url": "https://nocturnalharmony.org/moonlit-melodies",
      "types": ["M", "E"],
      "address": "456 Starlight Lane",
      "city": "Stardustville",
      "state": "CA",
      "postal_code": "67890",
      "country": "US",
      "approximate": "yes"
    },
    {
      "name": "Dusk Dance",
      "slug": "dusk-dance-11",
      "day": 4,
      "time": "18:00",
      "end_time": "21:00",
      "location": "Twilight Gardens",
      "group": "Eve's Elegance",
      "notes": "Outdoor event, dress warmly.",
      "updated": "2023-01-08 09:40:05",
      "url": "https://eveselegance.net/dusk-dance",
      "types": ["D", "S"],
      "address": "123 Evening Avenue",
      "city": "Moonrise City",
      "state": "FL",
      "postal_code": "54321",
      "country": "US",
      "approximate": "no"
    },
    {
      "name": "Starlit Soiree",
      "slug": "starlit-soiree-6",
      "day": 6,
      "time": "21:00",
      "end_time": "23:30",
      "location": "Celestial Ballroom",
      "group": "Starry Nights Society",
      "notes": "Formal attire required.",
      "updated": "2021-08-30 19:15:55",
      "url": "https://starrynights.org/starlit-soiree",
      "types": ["B", "G"],
      "address": "789 Galaxy Street",
      "city": "Nova Town",
      "state": "AZ",
      "postal_code": "56789",
      "country": "US",
      "approximate": "no"
    },
    {
      "name": "Twilight Tales",
      "slug": "twilight-tales-9",
      "day": 1,
      "time": "18:30",
      "end_time": "20:00",
      "location": "Enchanted Library",
      "group": "Mystic Chronicles",
      "notes": "Bring your favorite book to share.",
      "updated": "2022-11-02 12:10:20",
      "url": "https://mysticchronicles.org/twilight-tales",
      "types": ["L", "R"],
      "address": "567 Enchantment Lane",
      "city": "Spellcaster City",
      "state": "NY",
      "postal_code": "67812",
      "country": "US",
      "approximate": "yes"
    },
    {
      "name": "Nocturnal Nourishment",
      "slug": "nocturnal-nourishment-5",
      "day": 3,
      "time": "19:30",
      "end_time": "22:00",
      "location": "Midnight Bistro",
      "group": "Nightfall Culinary Club",
      "notes": "Reservations recommended.",
      "updated": "2023-06-20 08:45:40",
      "url": "https://nightfallculinaryclub.net/nocturnal-nourishment",
      "types": ["F", "C"],
      "address": "234 Moonlit Avenue",
      "city": "Gloomhaven",
      "state": "WA",
      "postal_code": "34567",
      "country": "US",
      "approximate": "no"
    },
    {
      "name": "Eclipse Empowerment",
      "slug": "eclipse-empowerment-7",
      "day": 5,
      "time": "17:00",
      "end_time": "19:00",
      "location": "Lunar Zen Center",
      "group": "Solstice Spirituality",
      "notes": "Open to all spiritual paths.",
      "updated": "2023-03-12 15:30:18",
      "url": "https://solsticespirituality.org/eclipse-empowerment",
      "types": ["Y", "M"],
      "address": "890 Eclipse Lane",
      "city": "Harmony Haven",
      "state": "CO",
      "postal_code": "45678",
      "country": "US",
      "approximate": "yes"
    },
    {
      "name": "Dawn Discovery",
      "slug": "dawn-discovery-2",
      "day": 6,
      "time": "05:30",
      "end_time": "07:00",
      "location": "Mystic Meadow",
      "group": "Rise and Shine Explorers",
      "notes": "Bring binoculars for birdwatching.",
      "updated": "2022-09-18 11:20:06",
      "url": "https://riseandshineexplorers.net/dawn-discovery",
      "types": ["N", "O"],
      "address": "345 Sunrise Avenue",
      "city": "Daybreak Village",
      "state": "OR",
      "postal_code": "23456",
      "country": "US",
      "approximate": "no"
    }
  ]